$ANSIBLE_VAULT;1.1;AES256
61353461313864333838303039356164646262613233336236383463366531613530643330376362
3739356161636531646431323132303262656435663339640a653464636437353039343537373738
63383737343739376234396533333935353839323435623534353561633637386530316234333637
6336366636356531350a663664636533333833663732363761313935306336343162356530373633
61643236326136653638306434656461376230393431303664346166643438643561376165313636
61303634323532616632653665656636366435396261643733613136333065346339636134323031
64653735366439656232353161366232333432653730623061353131333034376334613164353537
64383864643630636134386331343463313030353437386434643161366230663031393936333865
34303733366166393665663336623432303062363763313766363134633435393233316435656261
33393162636363396164616164373734396566613365356362333161313536313036646336386565
393566613763663866393336613231633734
