# roles/web/defaults/main.yml
web_service_name: nginx
web_root_path: /var/www/html
nginx_user: "{{ 'nginx' if ansible_distribution == 'Amazon' else 'www-data' }}"
nginx_port: 80
server_name: localhost

